server:
  port: 8081
spring:
  application:
    name: springcloud-user # 服务名称 横杠不可以是下划线

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_springcloud?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.coolron.user.domain
  mapper-locations: classpath:mapping/user/*.xml

eureka:
  client:
    # 指定服务注册中心的位置
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
sms: 'hahahahhahaha'
